# Make AdminRootController the root controller for the application so people
---
Name: recipe-adminroutes
After:
  - '#adminroutes'
---
# Set the default panel in the administration area
SilverStripe\Admin\AdminRootController:
  default_panel: MaximeRainville\GithubAudit\Admin\GitHub
